apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  limits:
    resources:
      cpu: 4
      memory: 16Gi
  provider:
    instanceProfile: karpenter-instance-profile
    amiFamily: AL2
    tags:
      accountingEC2Tag: karpenter
      eks/cluster-name: Worley-NC-EKS-Cluster
    subnetSelector:
      kubernetes.io/cluster/Worley-NC-EKS-Cluster: owned
    securityGroupSelector:
      kubernetes.io/cluster/Worley-NC-EKS-Cluster: owned
  requirements:
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - t3.medium
        - t3.large
        - t3.small
        - m5.large        # Added more options for flexibility
        - m5.xlarge       # Additional flexibility for scaling
  ttlSecondsAfterEmpty: 30
  consolidation:
    enabled: true  # Enables consolidation (resource packing) to optimize usage
