---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-k8s
  template:
    metadata:
      labels:
        app: ui-k8s
    spec:
      containers:
        - name: ui-k8s-nginx
          image: 484907523966.dkr.ecr.ap-south-1.amazonaws.com/worley-nc-ui-k8s:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ui-k8s-service
spec:
  selector:
    app: ui-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
