name: Terraform AWS Deployment

on:
  push:
    branches:
      - amey

jobs:
  TerraformAWS:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

    steps:
      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: ./
        if: success()

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./ # Point to your main Terraform directory
        if: success()

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan -input=false || echo "Terraform plan failed; review configuration."
        working-directory: ./
        if: success()

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve tfplan || echo "Terraform apply failed; review state and plan."
        working-directory: ./ # Point to your main Terraform directory
        if: success()

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
        if: success()

      - name: Apply ClusterRoleBinding for AWS Load Balancer Controller
        run: |
          kubectl apply -f modules/aws-lbc/aws-lb-controller-clusterrolebinding.yaml
        if: success()

      - name: Apply Kubernetes Resources
        run: |
          kubectl apply -f modules/eks/k8s.yml
        if: success()

      - name: Apply Ingress Resources
        run: |
          kubectl apply -f modules/eks/ingress.yml
        if: success()
