name: Terraform AWS Deployment

on:
  push:
    branches:
      - amey

jobs:
  TerraformAWS:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TERRAFORM_DIR: "./"

    steps:
      # Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize Terraform
      - name: Terraform Destroy
        run: terraform destroy
        working-directory: ${{ env.TERRAFORM_DIR }}
        if: success()

    #   # Validate Terraform configuration
    #   - name: Terraform Validate
    #     run: terraform validate
    #     working-directory: ${{ env.TERRAFORM_DIR }}
    #     if: success()

    #   # Plan Terraform execution
    #   - name: Terraform Plan
    #     run: terraform plan -out=tfplan -input=false
    #     working-directory: ${{ env.TERRAFORM_DIR }}
    #     if: success()

    #   # Apply Terraform configuration
    #   - name: Terraform Apply
    #     run: terraform apply -auto-approve tfplan
    #     working-directory: ${{ env.TERRAFORM_DIR }}
    #     if: success()
